---
repos:
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: "v5.0.0"
    hooks:
      - id: "trailing-whitespace"
        exclude: "^pulp_docs"
      - id: "end-of-file-fixer"
        exclude: "^pulp_docs"
      - id: "check-added-large-files"
      - id: "check-toml"

  - repo: "https://github.com/astral-sh/ruff-pre-commit"
    rev: "v0.11.10"
    hooks:
      # Run the linter.
      - id: "ruff-check"
        args: [ "--fix" ]
      # Run the formatter.
      - id: "ruff-format"

  - repo: "https://github.com/adrienverge/yamllint"
    rev: "v1.37.1"
    hooks:
      - id: "yamllint"
        files: ".*y[a]ml$"

  - repo: "https://github.com/crate-ci/typos"
    rev: "v1.32.0"
    hooks:
      - id: "typos"
        exclude: "(^tests)|(^docs)|(^pulp_docs)"
...
