---
name: "Docs CI"

on:
  workflow_call:
    inputs:
      pulpdocs_ref:
        description: "Git reference of this workflow file. Must match the one used for the workflow call"
        type: string
        required: true

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout pulp-docs repository"
        if: "${{ github.event.repository.name != 'pulp-docs' }}"
        uses: "actions/checkout@v4"
        with:
          repository: "pulp/pulp-docs"
          path: "pulp-docs"
          ref: "${{ inputs.pulpdocs_ref }}"
          fetch-depth: 0

      - name: "Checkout component repository"
        uses: "actions/checkout@v4"
        with:
          path: "${{ github.event.repository.name }}"
          fetch-depth: 0

      - name: "Instructions to run locally"
        run: |
          cat <<EOL
          == Checks

          * You have an up-to-date version of pulp-docs: https://github.com/pulp/pulp-docs
          * CWD is the pulp-docs repository root
          * The component dir is at the parent dir: '../${{ github.event.repository.name }}'
          * The component checkout matches: (TODO display correct commit here)

          == Command

          make docs-ci COMPONENT=${{ github.event.repository.name }}
          EOL

      - uses: "actions/setup-python@v5"
        with:
          python-version: "3.12"

      - name: "Install pulp-docs"
        working-directory: "pulp-docs"
        run: |
          pip install --upgrade pip
          pip install -r doc_requirements.txt

      - name: "Build Docs"
        working-directory: "pulp-docs"
        run: |
          COMPONENT="${{ github.event.repository.name }}"
          make docs-ci COMPONENT="$COMPONENT"

      - name: "Sanity Check"
        working-directory: "pulp-docs"
        run: |
          echo "Checking that the namespace for the component under CI exists in the built docs."
          ls "site/${{ github.event.repository.name }}"
...
