---
name: "Docs Test"

on:
  workflow_call:

jobs:
  build-docs:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
        with:
          repository: "pulp/pulp-docs"
          path: "pulp-docs"
          fetch-depth: 0

      # For non pulp-docs components
      # - uses: "actions/checkout@v4"
        # with:
          # path: "${{ github.event.repository.name }}"

      - name: "Set up Python"
        uses: "actions/setup-python@v5"
        with:
          python-version: "3.12"

      - name: "Install Test Dependencies"
        working-directory: "pulp-docs"
        run: |
          pip install --upgrade pip
          pip install -r doc_requirements.txt

      - name: "Build docs"
        working-directory: "pulp-docs"
        run: |
          pulp-docs ci . "../${{ github.event.repository.name }}" --step build

      - name: "Sanity Check"
        working-directory: "pulp-docs"
        run: |
          echo "Checking that the namespace for the component under CI exists in the built docs."
          ls "site/${{ github.event.repository.name }}/docs"
...
