---
name: "Docs Test"

on:
  workflow_call:

defaults:
  run:
    working-directory: "pulp-docs"

jobs:
  build-docs:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
        with:
          path: "pulp-docs"
          fetch-depth: 0

      - name: "Set up Python"
        uses: "actions/setup-python@v5"
        with:
          python-version: "3.12"

      - name: "Install Test Dependencies"
        run: |
          pip install -r doc_requirements.txt

      - name: "Build docs"
        run: |
          make docs
...
