---
name: "Publish pulpproject.org"
on:
  schedule:
    - cron: "00 3 * * 1-5"
  workflow_dispatch:

defaults:
  run:
    working-directory: "pulp-docs"

jobs:
  build-docs:
    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v6"
        with:
          fetch-depth: 0
          path: "pulp-docs"

      - name: "Install UV"
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0

      - name: "Build HTML site for pulpproject.org."
        shell: bash
        run: |
          make docs-prod
          tar cvf pulpproject.org.tar site

      - name: "Upload documentation site"
        uses: "actions/upload-artifact@v7"
        with:
          name: "pulpproject.org.tar"
          path: "pulp-docs/pulpproject.org.tar"
          if-no-files-found: "error"

  publish-docs:
    runs-on: "ubuntu-latest"
    needs:
      - "build-docs"

    env:
      PULP_DOCS_KEY: "${{ secrets.PULP_DOCS_KEY }}"

    steps:
      - uses: "actions/checkout@v6"
        with:
          fetch-depth: 1
          path: "pulp-docs"

      - name: "Download built docs"
        uses: "actions/download-artifact@v8"
        with:
          name: "pulpproject.org.tar"
          path: "pulp-docs/"

      - name: "Publish docs to pulpproject.org"
        run: |
          tar xf pulpproject.org.tar
          .github/workflows/scripts/publish_all_docs.sh "$(pwd)/site"
...
