---
name: "Update Data Branch"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0,3"  # every sunday and wednesday at midnight

jobs:
  update-data:
    runs-on: "ubuntu-latest"
    permissions:
      contents: "write"
    steps:
      - name: "Checkout docs-data branch"
        uses: "actions/checkout@v4"
        with:
          ref: "docs-data"

      - name: "Set up Python"
        uses: "actions/setup-python@v5"
        with:
          python-version: "3.12"

      - name: "List requirements"
        run: |
          cat requirements_ubuntu.txt
          cat requirements_python.txt

      - name: "Install System dependencies"
        run: |
          sudo apt -y install $(tr '\n' ' ' < requirements_ubuntu.txt)

      - name: "Install Python dependencies"
        run: |
          pip install --upgrade pip
          pip install -r requirements_python.txt

      - name: "Generate openapi json files and commit/push to docs-data branch"
        run: |
          git config user.name github-actions
          git config user.email github-action@github.com
          ./update-data.sh
...
